Chapter 2 bootcamp tutorials
intel/rohd pull request #278
Opened 2023-02-20 09:08 UTC by quekyj

## Description & Motivation

Added bootcamp chapter 2. Most of the bootcamp participants would like to see the generation of the system verilog code side by side. So, need to introduce a `Module` earlier than before just to show them the system verilog code. 

In chapter 2, it's going to be a quick touch and won't go deep into what is module yet as still some of the participants unfamiliar with SV. 

## Related Issue(s)

Nope

## Testing

Nope.

## Backwards-compatibility

> Is this a breaking change that will not be backwards-compatible? If yes, how so?

Nope.

## Documentation

> Does the change require any updates to documentation? If so, where? Are they included?

Nope.

2023-02-20 09:16 UTC, quekyj commented
I am not sure why its running fine in my local but there are problems in GH action.

![image](https://user-images.githubusercontent.com/115072593/220063380-5bfef06f-b670-48be-999b-0676f62b0bde.png)

2023-02-20 09:56 UTC, chykon commented
CI uses `dart analyze --fatal-infos` which will give an error code for info messages. However, your screenshot does not show that there are informational messages. I tried it in GitHub Codespaces - it gives the same as CI.

![Снимок экрана от 2023-02-20 12-50-02](https://user-images.githubusercontent.com/82272369/220072042-3e9c15e0-cdc3-4b6e-b32d-85ed3ecef69b.png)

Try cloning the repository again.

2023-02-21 05:49 UTC, quekyj commented
> CI uses `dart analyze --fatal-infos` which will give an error code for info messages. However, your screenshot does not show that there are informational messages. I tried it in GitHub Codespaces - it gives the same as CI.

Look like this is the problem with my version of dart. I need to update my dart version

2023-02-21 13:29 UTC, chykon reviewed
Small notes. I hope this doesn't annoy you :)

2023-02-21 13:29 UTC, chykon commented on doc/tutorials/Chapter_2/g_constant.dart
> +/// Copyright (C) 2023 Intel Corporation
There doesn't seem to be any references to this file in the text. Perhaps it is worth mentioning it, as it is done for other files?

2023-02-21 13:29 UTC, chykon commented on doc/tutorials/Chapter_2/h_bus_range_swizzling.dart
> +/// Copyright (C) 2023 Intel Corporation
There doesn't seem to be any references to this file in the text. Perhaps it is worth mentioning it, as it is done for other files?

2023-02-21 13:29 UTC, chykon commented on doc/tutorials/Content_Page.md
>    * [Docker Container Setup](./Chapter_1/01-Setup_Installation.md#docker-container-setup)
Maybe rename `assets/And_gate.png` to `assets/and_gate.png` to follow `snake_case`?

2023-02-21 17:28 UTC, mkorbel1 requested changes

2023-02-21 17:28 UTC, mkorbel1 commented on doc/tutorials/Content_Page.md
> +    * [How to use chapter template](./Chapter_2/00-Basic_Logic.
Broken link here

2023-02-21 18:06 UTC, mkorbel1 commented on doc/tutorials/Chapter_2/00-Basic_Logic.md
> +Note: This section of code **does not need to run**.
This note is a little confusing, better to say that it's not needed in the tutorial and is just an example, or something like that?

2023-02-21 18:06 UTC, mkorbel1 commented on doc/tutorials/Chapter_2/00-Basic_Logic.md
> +      portC = basicLogic.signals
this search using `firstWhere` seems unnecessary for the tutorial?  Why not just refer to the output?  Maybe related to previous comment about whether we should even use `Module` here

2023-02-21 18:06 UTC, mkorbel1 commented on doc/tutorials/Chapter_2/00-Basic_Logic.md
> +1. Create a constant of value 10 and assign to a Logic input.
Why to a "Logic input"?  Why not just to a "Logic"?

2023-02-21 18:06 UTC, mkorbel1 commented on doc/tutorials/Chapter_2/00-Basic_Logic.md
> +    final signal1 = addInput('a', a, width: a.width);
Again, making all these inputs and outputs is not really relevant for this tutorial and makes the code look more complex and verbose than it needs to

2023-02-23 01:40 UTC, quekyj commented
@chykon how to run the markdown lint on local before push?

2023-02-23 08:08 UTC, chykon commented
@quekyj If you are using VSCode you can

* install [extension](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint)
* open ROHD repository
* open `Command Palette` (Ctrl+Shift+P)
* type `Lint all Markdown files in the workspace with markdownlint` and run the command.

The extension will show violation of the rules for documents. Most errors can be corrected automatically (`RMB` -> `Format Document`).

Otherwise, you need to install [markdownlint-cli2](https://github.com/DavidAnson/markdownlint-cli2) and use it.

2023-02-24 00:35 UTC, mkorbel1 approved these changes
I think this looks good, nice work!

2023-02-24 00:36 UTC, merged