update chapter 2 bootcamp
intel/rohd pull request #310
Opened 2023-03-13 06:16 UTC by quekyj

## Description & Motivation

Update chapter 2 bootcamp by adding examples and fix assign statement does not show up. 

## Related Issue(s)

None

## Testing

None

## Backwards-compatibility

> Is this a breaking change that will not be backwards-compatible? If yes, how so?

No

## Documentation

> Does the change require any updates to documentation? If so, where? Are they included?

No

2023-03-13 17:49 UTC, mkorbel1 requested changes

2023-03-13 17:49 UTC, mkorbel1 commented on doc/tutorials/chapter_2/h_bus_range_swizzling.dart
> +  // Get a copy of f
Confusing comment, it's a copy with one bit set to 0 right?

2023-03-16 02:41 UTC, quekyj commented
Why is this a dead link in Github action? 

```
FILE: ./CONTRIBUTING.md
[✖] https://dart.dev/guides/language/effective-dart

22 links checked.

ERROR: 1 dead links found!
[✖] https://dart.dev/guides/language/effective-dart → Status: 0
```

2023-03-16 07:00 UTC, chykon commented
> Why is this a dead link in Github action?

You can try restarting CI after a while (maybe the site was down or DDoS protection worked), or add it to the ignore list (<https://github.com/intel/rohd/blob/main/.github/configs/mlc_config.json>) as we are sure this is a false positive.

When adding to the ignore list, it is advisable to adhere to the pattern:

* first `^`
* then `LINK`
* at the end of `$`

We use regular expression syntax to mark the start (`^`) and end (`$`) of text, which allows us to ignore only the address that exactly matches the specified one, and not any addresses that contain such a substring. An example is already on the ignore list itself.

2023-03-20 02:15 UTC, quekyj commented
> You can try restarting CI after a while (maybe the site was down or DDoS protection worked), or add it to the ignore list (https://github.com/intel/rohd/blob/main/.github/configs/mlc_config.json) as we are sure this is a false positive.

Do you think the whitelist should be added to this pull request or better separate it into other pull request instead?

2023-03-20 09:23 UTC, chykon commented
It would probably be worth making the changes related to the ignore settings in a separate PR, but I personally did not think about it until you rightly pointed it out. It's probably best to check with the maintainer of the repository.

2023-03-30 00:21 UTC, mkorbel1 approved these changes
Looks good!

2023-03-30 00:49 UTC, mkorbel1 commented
I think you need to pull master to fix the failing test

2023-04-03 23:43 UTC, merged