Vscode extension
intel/rohd pull request #437
Opened 2023-11-14 03:11 UTC by quekyj

## Description & Motivation

Add vscode rohd snippet for auto-completion feature in vscode. Users now can install ROHD vscode extension and then use the auto-completion feature to write code.

## Related Issue(s)

Nope.

## Testing

Manual testing.

## Backwards-compatibility

> Is this a breaking change that will not be backwards-compatible? If yes, how so?

no

## Documentation

> Does the change require any updates to documentation? If so, where? Are they included?

Added to vscode readme.

2023-12-01 23:07 UTC, mkorbel1 requested changes
Overall this looks great, I think it will be helpful for people getting started, nice work!

2023-12-01 23:07 UTC, mkorbel1 commented on vs_code/snippets/rohd.json
> +        "prefix": "vf",
maybe add "tb", "testbench" as prefixes?

2023-12-01 23:07 UTC, mkorbel1 commented on vs_code/snippets/rohd.json
> +            "  // TODO: Uncomment this if you think this is helpful.",
ditch the waitNegedges function, not necessary

2023-12-15 00:43 UTC, mkorbel1 commented on vs_code/example.dart
delete this?

2024-04-18 05:53 UTC, quekyj commented on vs_code/src/test/runTest.ts
no test is needed

2024-05-06 16:27 UTC, mkorbel1 commented on vs_code/CHANGELOG.md
> +- Initial release
@quekyj  can you fix this markdown lint issue?

2026-07-17 20:46 UTC, mkorbel1 commented
Superseded by https://github.com/intel/rohd/pull/670

2026-07-17 20:46 UTC, closed without merging